- src/autosuspend/checks/activity.py
The request url returns a error message (parse error) in Kodi 18.1.
I've adapted the url according to this description on the Kodi website: https://kodi.wiki/view/JSON-RPC_API/v9#XBMC.GetInfoBooleans
and tested it on my kodi system.
> Fix KodiIdleTime

- src/autosuspend/checks/activity.py
- tests/test_checks_activity.py
Kodi sets the Idle boolean to ```true``` when the given time in ```System.IdleTime(x)``` runs out and the user wasn't active for this amount of time. Hence the user is active when the returned boolean is ```false```.
I've updated the if clause according to this observation.
> Fix if clause in KodiIdleTime check

- .github/workflows/ci.yml
- setup.py
- src/autosuspend/checks/activity.py
- src/autosuspend/util/systemd.py
- tests/conftest.py
- tests/test_checks_activity.py
- tests/test_util_systemd.py
IdleHint is a boolean value in DBus schema
(https://www.freedesktop.org/wiki/Software/systemd/logind/),
it will have a falsy value, not "no" as a string when the session is not
idle.
Fixes #71.
> Fix IdleHint checking in LogindSessionsIdle

- doc/source/changelog.rst
- src/autosuspend/checks/__init__.py
- src/autosuspend/checks/activity.py
- src/autosuspend/checks/wakeup.py
- src/autosuspend/util/subprocess.py
- tests/test_checks_activity.py
- tests/test_checks_wakeup.py
* Ensure that errors that cannot be recovered are correctly classified
as SevereCheckErrors while others are consistently reported as
TemporaryCheckErrors.
* Catch some special cases such as missing binaries to execute and
report them as SevereCheckErrors.
* Always provide a custom explanation in reported exceptions.
> Improve error handling and make it consistent

- doc/source/installation.rst
- setup.py
Include an `all` package extra and use that one by default for the
from-source installation such that users receive all additional
requirements.
This provides the required installation instructions for testing #99
> Explain from-source installation with extras and branch

- doc/source/available_checks.rst
- doc/source/changelog.rst
- doc/source/conf.py
- src/autosuspend/checks/activity.py
- tests/test_checks_activity.py
Parses a log file and uses that first timestamp found when iterating the
file starting from the last line.
Will fix #98
> Implement a LastLogAcitivity check

- doc/source/changelog.rst
- src/autosuspend/checks/activity.py
- tests/test_checks_activity.py
Change the jsonpath parser to the ext module which provides support for
filter expressions.
Related to #102
> fix: use jsonpath ext to support filter expressions

- doc/source/available_checks.rst
- doc/source/external_command_activity_scripts.rst
- doc/source/faq.rst
- doc/source/index.rst
Adds the pyLoad user script from #102 to a new section with
user-provided scripts.
Some more clarifying words in the FAQ regarding this case are added here
too.
> docs: new section with ExternalCommand user scripts

- setup.py
tzlocal 3 has switched from pytz to zoneinfo as the timezone provider.
This has some strange side-effects that still need to be investigated.
As a temporary workaround, limit tzlocal to versions below 3. The
maintainer of tzlocal has indicated that the 2.x release line will be
supported for some time still.
> fix(ical): limit tzlocal to version <3

- doc/source/available_checks.rst
Adds a hint on how to configure permanent network interface names for
the bandwidth activity check.
Fixes #120
> docs(activity): add hint for permanent nic names

- setup.py
- tox.ini
tzlocal 3.0 has converted to the new Python 3.9 zoneinfo library as the
timezone provider. These timezone instances do not have the pytz
specific localize function. Therefore, tzlocal was pinned to versions < 3. With a compatibility layer now in place starting with tzlocal 4, this pinning isn't needed anymore.
> fix(ical): support tzlocal >= 4

- src/autosuspend/checks/xpath.py
We have now a conditional import on a different level to meet the
requirement that these dependencies are optional.
> refator: make lxml exports top-level statements

- src/autosuspend/__init__.py
Extends the log message indicating that the system is currently idle but not yet long enough with information since when the system is detected to be idle in seconds.
Related to: #281
> feat: add seconds since the system became idle to logs

- setup.py
- src/autosuspend/checks/ical.py
- tox.ini
Depending on the package version, tzlocal either returns a zoneinfo.ZoneInfo or a pytz timezone object. Provide a face method for localizing datetimes using any of the possible return types of tzlocal. This allows supporting all available tzlocal versions again.
> fix(ical): support all versions of tzlocal

- doc/source/available_checks.rst
- src/autosuspend/checks/systemd.py
- tests/test_checks_systemd.py
logind sessions have different classes. So far, all classes of logind sessions were taken into account. However, this might include greeter sessions by tools such as lightdm. With this commit, a new config option for the LogindSessionIdle check allows configuring which classes of sessions to look at. The default value restricts processing to users sessions as a sensible default.
BREAKING CHANGE: LogindSessionIdle now only processes sessions of type "user" by default. Use the new configuration option classes to also include other types in case you need to include them in the checks.
Fixes: #366
> feat(logind)!: configure which session classes to process

- .github/workflows/ci.yml
- tox.ini
Adds Python 3.11 into tests and deprecates Python 3.8 support, which is not part of Debian oldstable anymore.
BREAKING CHANGE: Python 3.8 has been deprecated and is not officially
supported anymore.
> build!: modernize supported Python version

- src/autosuspend/__init__.py
- tests/test_integration.py
Allows printing the currently installed version of autosuspend.
Fixes: #482
> feat(cli): provide a version subcommand

- .github/workflows/ci.yml
That makes things easier to understand than using a commit hash.
> ci: use a semantic version for the checkout action

- .github/workflows/ci.yml
- pyproject.toml
- src/autosuspend/__init__.py
- src/autosuspend/checks/__init__.py
- src/autosuspend/checks/command.py
- src/autosuspend/checks/ical.py
- src/autosuspend/checks/json.py
- src/autosuspend/checks/kodi.py
- src/autosuspend/checks/linux.py
- src/autosuspend/checks/logs.py
- src/autosuspend/checks/mpd.py
- src/autosuspend/checks/smb.py
- src/autosuspend/checks/stub.py
- src/autosuspend/checks/systemd.py
- src/autosuspend/checks/util.py
- src/autosuspend/checks/xorg.py
- src/autosuspend/checks/xpath.py
- src/autosuspend/util/__init__.py
- src/autosuspend/util/datetime.py
- tests/conftest.py
- tests/test_autosuspend.py
- tests/test_checks.py
- tests/test_checks_command.py
- tests/test_checks_ical.py
- tests/test_checks_json.py
- tests/test_checks_util.py
- tests/test_checks_xpath.py
- tests/utils.py
- tox.ini
* Add 3.12
* Drop support for 3.9
> Modernize Python versions

- src/autosuspend/checks/kodi.py
This commit fixes a syntax error in the request sent to Kodi in the KodiIdleTime check. A sample request from autosuspend is following:
`{{"jsonrpc": "2.0", "id": 1, "method": "XBMC.GetInfoBooleans","params": {"booleans": ["System.IdleTime(300)"]}}`
It has a surplus opening curly brace at the beginning, leading Kodi to ignore the request with the following log entry:
`error <general>: JSONRPC: Failed to parse [the above request]`
This leads to the following exception in autosuspend:
```
autosuspend.Processor - WARNING - Check kodi-browsing[class=KodiIdleTime] failed. Ignoring... Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/autosuspend/checks/kodi.py", line 93, in check
if not reply["result"][f"System.IdleTime({self._idle_time})"]:
~~~~~^^^^^^^^^^
KeyError: …
```
> KodiIdleTime: Remove surplus brace

- .github/workflows/ci.yml
- tox.ini
Things worked before. However, now the project is tested on 3.13, too.
> feat: official Python 3.13 support

- data/autosuspend.service
- doc/source/systemd_integration.rst
Declares the autosuspend-detect-suspend.service in the Also section of the autosuspend systemd unit. That way, the suspend unit is enabled/disabled together with the main unit and users don't have to remember activating/deactivating this unit.
Cf.: #625
> feat(systemd): automatically enable/disable suspend hook

- .github/workflows/ci.yml
- .readthedocs.yaml
Otherwise, the diagram is missing there.
> docs: properly install plantuml on readthedocs

- setup.py
- src/autosuspend/checks/ical.py
- src/autosuspend/checks/logs.py
- src/autosuspend/util/datetime.py
- tests/test_checks_ical.py
- tests/test_checks_logs.py
pytz has become obsolete nowadays. However, we might need tzdata on some systems, which is a new dependency maintained by PSF.
BREAKING CHANGE: new optional dependency tzdata when doing log parsing
> refactor(deps): remove pytz, require tzdata
